engines:
  duplication:
    enabled: true
    config:
      languages:
      - "php"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
ratings:
  paths:
  - "**.php"
exclude_paths:
  - "examples/**/*"
  - "test/**/*"
  - "vendor/**/*"